kibot:
  version: 1

import:
  - manufacturers/PCBWay.kibot.yaml

outputs:

  - name: gerbers
    comment: Gerbers compatible with PCBWay
    type: gerber
    dir: manufacturing/default/gerbers
    options: &gerber_options
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: true
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: true
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: true
      create_gerber_job_file: false
      output: "%f.%x"
      gerber_precision: 4.6
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false
      disable_aperture_macros: true
      line_width: 0.1
      subtract_mask_from_silk: false
      inner_extension_pattern: '.gl%N'
    layers:
      - copper
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - F.Paste
      - B.Paste
      - Edge.Cuts

  - name: drill
    comment: Drill files compatible with PCBWay
    type: excellon
    dir: manufacturing/default/gerbers
    options:
      metric_units: false
      minimal_header: true
      zeros_format: SUPPRESS_LEADING
      # left_digits: 3
      # right_digits: 3
      # See https://github.com/INTI-CMNB/kicad-ci-test-spora/issues/1
      # and https://docs.oshpark.com/design-tools/gerbv/fix-drill-format/
      left_digits: 2
      right_digits: 4
      pth_and_npth_single_file: false
      pth_id: ''
      npth_id: '-NPTH'
      output: "%f%i.drl"

  - name: generate_pos
    comment: "Generate position file"
    type: position
    dir: manufacturing/default/position
    options:
      format: 'ASCII' # [ASCII,CSV] Format for the position file.
      separate_files_for_front_and_back: true
      units: millimeters # Units used for the positions.
      output: '%i.%x' # Output file name (%i='top_pos'|'bottom_pos'|'both_pos', %x='pos'|'csv'). Affected by global options.

  - name: print_sch_svg
    comment: "Print schematic (SVG)"
    type: svg_sch_print
    dir: .
    options:
      output: 'docs/svg/%f-%i%v.%x'

  - name: print_sch_pdf
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: .
    options:
      output: 'docs/pdf/%f-%i%v.%x'

  - name: print_pcb_pdf
    comment: "Print pdf"
    type: pdf
    dir: .
    options:
      output: 'docs/pdf/%f-%i%v.%x'
    layers:
      - copper
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - F.Paste
      - B.Paste
      - Edge.Cuts

  - name: print_pcb_svg
    comment: "Print svg"
    type: svg
    dir: .
    options:
      output: 'docs/svg/%f-%i%v.%x'
    layers:
      - copper
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - F.Paste
      - B.Paste
      - Edge.Cuts