name: Kicad project

on:
  push:
    branches:
      - '**'
    tags:
      - 'v**'

jobs:
  build:
    name: Generate KiCad outputs
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: dropbot_control_board
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt install -y zip unzip
        python -m pip install --upgrade pip
        python -m pip install git+https://github.com/ryanfobel/KiField.git@add-quantity
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - uses: INTI-CMNB/KiBot@v1
      with:
        # Required - kibot config file
        config: .kicad_helpers_config/config.kibot.yaml
        # optional - schematic file
        schema: '${{ env.PROJECT_NAME }}.sch'
        # optional - PCB design file
        board: '${{ env.PROJECT_NAME }}.kicad_pcb'
    - name: Get the commit hash
      id: get_commit_hash
      run: echo ::set-output name=GIT_HASH::$(git rev-parse --short "$GITHUB_SHA")
    - name: Generate BOM
      run: |
        sudo chown -R runner:docker manufacturing
        mkdir -p manufacturing/default/assembly_photos
        mkdir -p manufacturing/PCBWay/assembly_photos
        python -m kifield --group -aq -x "${{ env.PROJECT_NAME }}.sch" -i "manufacturing/default/${{ env.PROJECT_NAME }}-BOM.csv"
        cp "manufacturing/default/${{ env.PROJECT_NAME }}-BOM.csv" "manufacturing/PCBWay/${{ env.PROJECT_NAME }}-BOM.csv"
    - name: Copy assembly photos to manufacturing
      run: |
        cp docs/png/front.png manufacturing/default/assembly_photos/front.png
        cp docs/png/back.png manufacturing/default/assembly_photos/back.png
        cp -r manufacturing/default/assembly_photos/*.png manufacturing/PCBWay/assembly_photos/
    - name: Upload BOM artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PROJECT_NAME }}-BOM-${{ steps.get_commit_hash.outputs.GIT_HASH }}
        path: manufacturing/default/${{ env.PROJECT_NAME }}-BOM.csv
    - name: Upload default manufacturing files
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PROJECT_NAME }}-default-manufacturing-files-${{ steps.get_commit_hash.outputs.GIT_HASH }}
        path: manufacturing/default
    - name: Upload PCBWay manufacturing files
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PROJECT_NAME }}-PCBWay-manufacturing-files-${{ steps.get_commit_hash.outputs.GIT_HASH }}
        path: manufacturing/PCBWay
    - name: Upload docs
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PROJECT_NAME }}-docs-${{ steps.get_commit_hash.outputs.GIT_HASH }}
        path: docs
    - name: Get the version
      if: startsWith(github.ref, 'refs/tags/v')
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Zip artifacts for release
      if: startsWith(github.ref, 'refs/tags/v')
      env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: |
        cd manufacturing/default && zip -r ../../${{ env.PROJECT_NAME }}-default-manufacturing-files-${VERSION}.zip * && cd ../..
        cd manufacturing/PCBWay && zip -r ../../${{ env.PROJECT_NAME }}-PCBWay-manufacturing-files-${VERSION}.zip * && cd ../..
        zip -r ${{ env.PROJECT_NAME }}-docs-${VERSION}.zip docs
        mv manufacturing/default/${{ env.PROJECT_NAME }}-BOM.csv ${{ env.PROJECT_NAME }}-BOM-${VERSION}.csv
        zip -rj ${{ env.PROJECT_NAME }}-gerbers-${VERSION}.zip manufacturing/default
    - name: Create release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.zip,*-BOM-*.csv"
        #bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}
